### ISSUE TITLE
Zero effectiveness of raider's bionic bodypart [with Compressed Raid enabled]

### ISSUE THREAD

**Issue by Reiquard** [emipa606/NewLimbsNeedsTraining#3]
Raiders with bionics _(which is possible with Compressed Raid enabled)_ have 0 effectiveness of that bionic bodypart at the moment of appearance

![screenshot6](https://user-images.githubusercontent.com/62316596/235521904-72446d81-4a32-4b2e-83fa-267899b217c3.png)

**Comment by emipa606** [comment]
This is strange as the age of the bionics is set to a random value above the limit for required training. Is this only with the compressed raids active?

**Comment by Reiquard** [comment]
Here are the mods for the test environment presented above:

    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
    <li>twsta.compressedraid.latest</li>
    <li>mlie.newlimbsneedstraining</li>

> Is this only with the compressed raids active?

Just tested with these mods:

    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
    <li>mlie.newlimbsneedstraining</li>

And here's the result

![screenshot8](https://user-images.githubusercontent.com/62316596/235787175-5e1c436f-43ab-40f3-ad2c-9bb7973cc9c8.png)

So the answer is **yes**, this happens with the [Compressed Raid](https://steamcommunity.com/sharedfiles/filedetails/?id=2927368319) active

**Comment by emipa606** [comment]
Fixed in 0ede26d
Thanks for the detailed report!
